### ISSUE TITLE
feat: Stack

### ISSUE THREAD

**Issue by msaug** [keep-starknet-strange/quaireaux#16]
# Feature Request

**Describe the Feature Request**

Implement a Stack data structure in Cairo 1.0

**Describe Preferred Solution**

[EDIT] After discussing it, the stack should be implemented using a dictionary.
The stack should expose three "main" methods to the user : `new`, `pop` and `push`. On top of that, we can implement utility functions such as `len`, `peek` and `is_empty`.

**Describe Alternatives**

**Related Code**

```
struct Stack<T> {
    elements: Array::<T>, 
}

trait StackTrait<T> {
    fn new() -> Stack::<T>;
    fn push(ref self: Stack::<T>, value: T);
    fn pop(ref self: Stack::<T>) -> Option::<T>;
    fn peek(ref self: Stack::<T>) -> Option::<T>;
    fn len(ref self: Stack::<T>) -> usize;
    fn is_empty(ref self: Stack::<T>) -> bool;
}
```
**Additional Context**

While the Stack implementation seems pretty trivial, I have given a try at it and encountered two major issues that should be solved with the next release of Cairo 1.

- Variable was previously moved
Here's a snippet of code illustrating the problem
```
// Variable was previously moved
fn peek(ref self: Stack::<T>) -> Option::<T> {
        let mut elements = self.elements;
        let mut last_index = elements.len() - 1_usize;
        let last = elements.get(last_index);
        self = Stack { elements };
        last
}
```
Hypothesis: the borrow checker complains here because I took ownership of `self` in the operation `elements.len() - 1_usize`. Therefore, I can't reuse it later in the code. This would require generic type `T` to implement the `Dup` trait (explanation from @spapinistarkware) which is a feature that will soon be implemented.

- Variable not dropped.
A variable that is declared and not returned at the end of a function generates the error `Variable not dropped.` I guess the comment above for the `Dup` trait stands for the `Drop` trait as well.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by spapinistarkware** [comment]
Implementating a stack using an Array is impossible, so good thing the compiler stopped you:)
We can only append to the end of the array, or pop from the front. So a queue is ok, a stack isn't. This has to do with Cairo's immutable memory model.
A stack could be implemented on top of a dictionary though

**Comment by spapinistarkware** [comment]
And yes, something like peek would require Dup or snapshots (an upcoming feature), so I'll probably add a message here when it's done

**Comment by msaug** [comment]
> We can only append to the end of the array, or pop from the front

I was thinking about duplicating the array in another memory segment without its last element

**Comment by spapinistarkware** [comment]
Yeah, that could work. It would restrict you to use inly Dup T's, while the dict impl doesn't, but peek would give you a snapshot (similar to rust reference).
I think dict makes more sense

**Comment by danilowhk** [comment]
@msaug @spapinistarkware  I just opened a PR of the Dict implementation of  Stack(still need to fix some compilation errors, which wasnt present when I was trying in another repo).

But I as its still WIP, I wanted to make 2 questions around Cairo V1:

1. In Cairo V1 do we still need the "start_word_dict"? 
https://github.com/danilowhk/quaireaux/blob/37580e6291ee267eb8d7fb40e303f9b27521db45/src/data_structures/stack.cairo#L26

2. In CairoV1 , lets say we use uint256 or any other struct(that uses more than 1 felt) as "value". In this case, when "updating len" do we have to go up by 2(in case of uin256) and N(in case of another struct that needs N felts in memory)? Or is this part abstracted and we just up 1 by 1?

https://github.com/danilowhk/quaireaux/blob/37580e6291ee267eb8d7fb40e303f9b27521db45/src/data_structures/stack.cairo#L59

These are the 2 questions that came to mind when trying to implement Stack in Dict. Also please let me know if there is any part of the code that could be done more efficiently, as I believe we are aiming for the most "efficient" code for 
quaireaux I guess.

**Comment by ClementWalter** [comment]
@msaug for reference implementation in cairo 0.x using dicts, see https://github.com/sayajin-labs/kakarot/blob/main/src/kakarot/stack.cairo

**Comment by msaug** [comment]
@danilowhk regarding 1. I believe we don't need to keep track of `start_dict` and `end_dict` in Cairo 1, the dictionary can be created and modified like this:
```rust
    let mut d = DictFeltToTrait::new();
    d.insert('First', 1);
    let a = d.get('First');
    d.squash();
```
For 2. since we're indexing a dictionary by felt we just need to increment/decrement length by one
