### ISSUE TITLE
feat: LinkedList

### ISSUE THREAD

**Issue by dubzn** [keep-starknet-strange/quaireaux#18]
# Feature Request

**Describe the Feature Request**

Implement a LinkedList data structure in Cairo 1.0. Based on this [Rust reference](https://github.com/TheAlgorithms/Rust/blob/master/src/data_structures/linked_list.rs).

**Describe Preferred Solution**

The LinkedList should expose this methods to the user : 
```
- new() -> LinkedList::<T>
- add(ref self: LinkedList::<T>element: T, index: felt);
- add_first(ref self: LinkedList::<T>, element: T);
- add_last(ref self: LinkedList::<T>, element: T);
- remove(ref self: LinkedList::<T>, index: felt) -> Option::<T>;
- remove_first(ref self: LinkedList::<T>) -> Option::<T>;
- remove_last(ref self: LinkedList::<T>) -> Option::<T>;
- get(ref self: LinkedList::<T>, index: felt) -> Option::<T>;
- is_empty(ref self: LinkedList::<T>) -> bool;
- len(ref self: LinkedList::<T>) -> usize;
```

Node:
```
struct Node<T> {
    val: T,
    next: Option<Node<T>>,
    prev: Option<Node<T>>,
}
```
LinkedList:
```
struct LinkedList<T> {
    length: usize,
    head: Option<Node<T>>,
    tail: Option<Node<T>>,
}
```

**Describe Alternatives**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by sdgalvan** [comment]
If you guys are ok with this impl, i can take it :P ❤️

**Comment by sdgalvan** [comment]
There may be some syntax errors, but it's because I'm not that used to Cairo 1 yet. Mainly aiming to validate the interface.

**Comment by msaug** [comment]
Can we use `Box` to manipulate pointers yet? Otherwise I'm not sure this is doable yet

**Comment by EvolveArt** [comment]
> Can we use `Box` to manipulate pointers yet? Otherwise I'm not sure this is doable yet

Looks like we can https://github.com/starkware-libs/cairo/blob/main/examples/fib_box.cairo

**Comment by msaug** [comment]
https://github.com/starkware-libs/cairo/pull/2178 recursive structs now available

**Comment by sdgalvan** [comment]
Nicee i was waiting for that, lemme do this in a few days. Im on vacations haha but i want to take it in 5 or 6 days (:pray:)

**Comment by tarrencev** [comment]
We'd love this for https://github.com/dojoengine/dojo. Let me know if there is anything I can help with!

**Comment by drspacemn** [comment]
Any news on this? I was not able to use recursive structs for the Trie implementation. Did someone sort it out for this?

**Comment by dubzn** [comment]
Indeed I couldn't finish it because of that issue, so I'm waiting for an update in cairo to be able to move forward. To provide context, I couldn't progress because of this issue: https://github.com/starkware-libs/cairo/issues/2249 (I also checked telegram chats to validate it)
