### ISSUE TITLE
feat: MergeSort

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/quaireaux#23]
# Feature Request

**Describe the Feature Request**
Implement a MergeSort algorithm in Cairo 1.0. Based out of [this](https://github.com/Astraly-Labs/Empiric/blob/master/contracts/starknet/lib/time_series/sorting.cairo#L10) Cairo 0 implementation.

**Describe Preferred Solution**

It includes utils methods on `Array` like `split_array` and `fill_array` as those are needed for the sorting algorithm to work.
The main `mergesort_elements` function has the following signature

```cairo
fn mergesort_elements(mut arr: Array::<u32>) -> Array::<u32>
```

An internal function `_merge` just merges two arrays together : 
```cairo
fn _merge(
    mut left_arr: Array::<u32>,
    mut right_arr: Array::<u32>,
    mut result_arr: Array::<u32>,
    left_arr_ix: u32,
    right_arr_ix: u32
) -> Array::<u32>
```

The first implementation is not generic as we would need to be able to restrict generic type parameters by trait in order to apply `<` operator on elements.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by ftupas** [comment]
Hello there, may I take this one?

**Comment by EvolveArt** [comment]
> Hello there, may I take this one?

I've already done most of the work on it, will submit a PR. Happy to get your help on it tho!

**Comment by ftupas** [comment]
> I've already done most of the work on it, will submit a PR. Happy to get your help on it tho!

Ah cool no worries! I'll try to get another one 🙂 Just saw the pr, looking good 💪
