### ISSUE TITLE
feat: Binary search tree

### ISSUE THREAD

**Issue by gaetbout** [keep-starknet-strange/quaireaux#27]
# Feature Request

**Describe the Feature Request**

Implementing a basic Binary Search Tree of type felt,

**Describe Preferred Solution**

The structure should look like:
```
struct Node {
   value: felt,
   left: Option<Node>,
   right Option<Node>
}
```

And it should comply to this interface: 

```
fn new(value: felt) -> Node;

fn get_value() -> felt;
fn set_value(new_value: felt) -> felt;

fn get_left() -> Option<Node>;
fn set_left(Node);

fn get_right() -> Option<Node>;
fn set_right(Node);

fn height() -> usize;
fn size() -> usize; 

fn is_leaf() -> bool;
fn contains(value: felt) -> bool; 

fn insert(value: felt);
fn delete(value: felt);
```
Insert should keep the tree sorted 

**Possible improvement**

1. Replace felt type with a generic and impl the useful traits (Like equals, compare, etc etc)
2. When iterators will be available some traversal methods could be added:
    - Pre-order Traversal
    - In-order Traversal
    - Post-order Traversal
    - Level-order Traversal
3. Could add some funky methods such as sum, max, min, avg (any other?)

**If the feature request is approved, would you be willing to submit a PR?**

- [x] Yes
- [ ] No

**Comment by abdelhamidbakhta** [comment]
Thanks @gaetbout , would love to accept a PR for this feature

**Comment by gaetbout** [comment]
**ON PAUSE**

Cairo1.0 doesn't allow (yet) structs referencing themselves.
Will resume whenever it is allowed
