### ISSUE TITLE
feat: Array extension - An extension to the existing ArrayTrait

### ISSUE THREAD

**Issue by gaetbout** [keep-starknet-strange/quaireaux#46]
# Feature Request

**Describe the Feature Request**

An extension to the existing ArrayTrait trait

**Related Code**

It should comply to the interface:

```rust
trait ArraySearchExt<T> {
    fn contains(ref self: Array::<T>, item: T) -> bool;
    fn index_of(ref self: Array::<T>, item: T) -> usize;
    fn occurrences_of(ref self: Array::<T>, item: T) -> usize;
}
```
As felt252 doesn't support PartialOrd I decided to make a new Trait to not add another constraint on ArraySearchExt
```rust
trait ArrayMinMaxExt<T> {
    fn min(ref self: Array::<T>) -> T;
    fn index_of_min(ref self: Array::<T>) -> usize;
    fn max(ref self: Array::<T>) -> T;
    fn index_of_max(ref self: Array::<T>) -> usize;
}
```
**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by gaetbout** [comment]
Ongoing

**Comment by gaetbout** [comment]
Need:
https://github.com/starkware-libs/cairo/issues/2151

**Comment by msaug** [comment]
We should not implement methods for array mutability.
Instead of manipulating mutations of existing arrays, which involve many copy operations, we should create a dict-based `Vec` data structure to handle mutation.

However, I agree that append-only and search-related functions will be helpful for the Array (which is actually a Queue?) data-structure

**Comment by gaetbout** [comment]
> We should probably not implement methods for array mutability. Instead of manipulating mutations of existing arrays, which involve many copy operations, we should create a dict-based `Vec` data structure to handle mutation.
> 
> However, I agree that append-only and search-related functions will be helpful for the Array (which is actually a Queue?) data-structure

It is indeed a queue:
https://github.com/starkware-libs/cairo/pull/2167

**Comment by gaetbout** [comment]
> We should probably not implement methods for array mutability. Instead of manipulating mutations of existing arrays, which involve many copy operations, we should create a dict-based `Vec` data structure to handle mutation.
> 
> However, I agree that append-only and search-related functions will be helpful for the Array (which is actually a Queue?) data-structure

So you are proposing that I create a dict-based implementation of an array or should I wait SW to make something like this?
