### ISSUE TITLE
feat: Queue (data structure)

### ISSUE THREAD

**Issue by sdgalvan** [keep-starknet-strange/quaireaux#7]
# Feature Request

Implement Queue data structure, [reference implementation (Rust)](https://github.com/TheAlgorithms/Rust/blob/master/src/data_structures/queue.rs).

**Describe Preferred Solution**
Create a Cairo file with Queue data structure based on Rust solution.

- Implement Queue
- Add the data structure to the data_structures module
- Units tests

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by chirag-bgh** [comment]
I would like to take this one.
