### ISSUE TITLE
feat: array ext with span

### ISSUE THREAD

**Issue by gaetbout** [keep-starknet-strange/quaireaux#75]
# Feature Request

**Describe the Feature Request**

At the moment array ext mostly takes @Array<T>, to be convenient it should also work with Span<T>.

Will work on this whenever https://github.com/keep-starknet-strange/quaireaux/pull/74 is done.

**Comment by naelob** [comment]
Hey ! I would love to work on this one ! Can you specify the Span type please, I cant find it inside the doc.
Thanks

**Comment by naelob** [comment]
I found this one : 
// Span.
struct Span<T> {
    snapshot: @Array<T>
}
Let me know if its right

**Comment by gaetbout** [comment]
Hey, 
Yep, it is that one. 
We first need #74 to be merged, and it is still changing a bit, it is also linked to some bugs, so it could be that it'll take some time. 
I also wrote in this issue that was going to work on it whenever 74 is solved/merged 🙁
